root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
delay = 1000
exclude_dir = ["vendor", "tmp", "test"]
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "500ms"
send_interrupt = true

[log]
time = false
