services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://t3m8ch@psql/productsdb

  psql:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=productsdb
      - POSTGRES_USER=t3m8ch
    healthcheck:
      test: "pg_isready --username=t3m8ch --database=productsdb"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
