[project]
name = "volumes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.10",
    "pydantic>=2.10.6",
    "uvicorn>=0.34.0",
]
